# Local PostGIS Docker (5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/fundacion_aseo?currentSchema=public&amp;useLobLocator=false
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.properties.hibernate.connection.autocommit=false
spring.datasource.hikari.pool-name=FundacionAseoHikariLocalPool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

# Same JPA settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always

# Multipart config
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
